# バージョン指定
FROM golang:latest
# ローカルファイルをワークフォルダに追加
ADD . /go/src
# ワークフォルダに変更
WORKDIR /go/src
# モジュールを使用可能にする
RUN go env -w GO111MODULE=auto
RUN go get github.com/gorilla/websocket
# 起動時に実行するコマンド
CMD ["go", "run", "main.go"]